// <auto-generated />
namespace ClassicJaguars.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class datesoldnullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datesoldnullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201507300730184_datesold nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
